//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyCompany", Namespace="http://schemas.datacontract.org/2004/07/MyWCF")]
    [System.SerializableAttribute()]
    public partial class MyCompany : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiplomaTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequiredEducationLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequiredExperienceYearsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int experienceYearsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int telField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiplomaTitle {
            get {
                return this.DiplomaTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DiplomaTitleField, value) != true)) {
                    this.DiplomaTitleField = value;
                    this.RaisePropertyChanged("DiplomaTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequiredEducationLevel {
            get {
                return this.RequiredEducationLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.RequiredEducationLevelField, value) != true)) {
                    this.RequiredEducationLevelField = value;
                    this.RaisePropertyChanged("RequiredEducationLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequiredExperienceYears {
            get {
                return this.RequiredExperienceYearsField;
            }
            set {
                if ((this.RequiredExperienceYearsField.Equals(value) != true)) {
                    this.RequiredExperienceYearsField = value;
                    this.RaisePropertyChanged("RequiredExperienceYears");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int experienceYears {
            get {
                return this.experienceYearsField;
            }
            set {
                if ((this.experienceYearsField.Equals(value) != true)) {
                    this.experienceYearsField = value;
                    this.RaisePropertyChanged("experienceYears");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int i {
            get {
                return this.iField;
            }
            set {
                if ((this.iField.Equals(value) != true)) {
                    this.iField = value;
                    this.RaisePropertyChanged("i");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tel {
            get {
                return this.telField;
            }
            set {
                if ((this.telField.Equals(value) != true)) {
                    this.telField = value;
                    this.RaisePropertyChanged("tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyCompany")]
    public interface IMyCompany {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompany/GetJobsForCompany", ReplyAction="http://tempuri.org/IMyCompany/GetJobsForCompanyResponse")]
        System.Data.DataTable GetJobsForCompany();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompany/AddJobForCompany", ReplyAction="http://tempuri.org/IMyCompany/AddJobForCompanyResponse")]
        bool AddJobForCompany(MyWeb.ServiceReference1.MyCompany e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompany/AddDiplomaForCandidate", ReplyAction="http://tempuri.org/IMyCompany/AddDiplomaForCandidateResponse")]
        bool AddDiplomaForCandidate(MyWeb.ServiceReference1.MyCompany e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompany/AddCompany", ReplyAction="http://tempuri.org/IMyCompany/AddCompanyResponse")]
        bool AddCompany(MyWeb.ServiceReference1.MyCompany e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompany/SignUp", ReplyAction="http://tempuri.org/IMyCompany/SignUpResponse")]
        bool SignUp(MyWeb.ServiceReference1.MyCompany e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompany/GetJobForCandidates", ReplyAction="http://tempuri.org/IMyCompany/GetJobForCandidatesResponse")]
        MyWeb.ServiceReference1.MyCompany[] GetJobForCandidates(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompany/GetCandidatesForJob", ReplyAction="http://tempuri.org/IMyCompany/GetCandidatesForJobResponse")]
        MyWeb.ServiceReference1.MyCompany[] GetCandidatesForJob(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompany/GetCandidate", ReplyAction="http://tempuri.org/IMyCompany/GetCandidateResponse")]
        MyWeb.ServiceReference1.MyCompany[] GetCandidate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyCompany/GetJobs", ReplyAction="http://tempuri.org/IMyCompany/GetJobsResponse")]
        MyWeb.ServiceReference1.MyCompany[] GetJobs();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyCompanyChannel : MyWeb.ServiceReference1.IMyCompany, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyCompanyClient : System.ServiceModel.ClientBase<MyWeb.ServiceReference1.IMyCompany>, MyWeb.ServiceReference1.IMyCompany {
        
        public MyCompanyClient() {
        }
        
        public MyCompanyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyCompanyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyCompanyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyCompanyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetJobsForCompany() {
            return base.Channel.GetJobsForCompany();
        }
        
        public bool AddJobForCompany(MyWeb.ServiceReference1.MyCompany e) {
            return base.Channel.AddJobForCompany(e);
        }
        
        public bool AddDiplomaForCandidate(MyWeb.ServiceReference1.MyCompany e) {
            return base.Channel.AddDiplomaForCandidate(e);
        }
        
        public bool AddCompany(MyWeb.ServiceReference1.MyCompany e) {
            return base.Channel.AddCompany(e);
        }
        
        public bool SignUp(MyWeb.ServiceReference1.MyCompany e) {
            return base.Channel.SignUp(e);
        }
        
        public MyWeb.ServiceReference1.MyCompany[] GetJobForCandidates(int id) {
            return base.Channel.GetJobForCandidates(id);
        }
        
        public MyWeb.ServiceReference1.MyCompany[] GetCandidatesForJob(int id) {
            return base.Channel.GetCandidatesForJob(id);
        }
        
        public MyWeb.ServiceReference1.MyCompany[] GetCandidate() {
            return base.Channel.GetCandidate();
        }
        
        public MyWeb.ServiceReference1.MyCompany[] GetJobs() {
            return base.Channel.GetJobs();
        }
    }
}
