/*1354632219,173220391*/

if (self.CavalryLogger) { CavalryLogger.start_js(["wK+uk"]); }

__d("Cookie",["Env"],function(a,b,c,d,e,f){var g=b('Env'),h={set:function(i,j,k,l,m){if(g.no_cookies&&i!='tpa')return;document.cookie=i+"="+encodeURIComponent(j)+"; "+(k?"expires="+(new Date(Date.now()+k)).toGMTString()+"; ":"")+"path="+(l||'/')+"; domain="+window.location.hostname.replace(/^.*(\.facebook\..*)$/i,'$1')+(m?"; secure":"");},clear:function(i,j){j=j||'/';document.cookie=i+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; "+"path="+j+"; domain="+window.location.hostname.replace(/^.*(\.facebook\..*)$/i,'$1');},get:function(i){var j=document.cookie.match('(?:^|;\\s*)'+i+'=(.*?)(?:;|$)');return (j?decodeURIComponent(j[1]):j);}};e.exports=h;});
__d("legacy:cookie",["Cookie"],function(a,b,c,d){var e=b('Cookie');a.getCookie=e.get;a.setCookie=e.set;a.clearCookie=e.clear;},3);
__d("AsyncSignal",["Env","ErrorUtils","QueryString","URI","XHR","copyProperties"],function(a,b,c,d,e,f){var g=b('Env'),h=b('ErrorUtils'),i=b('QueryString'),j=b('URI'),k=b('XHR'),l=b('copyProperties');function m(n,o){this.data=o||{};if(g.tracking_domain&&n.charAt(0)=='/')n=g.tracking_domain+n;this.uri=n;}m.prototype.setHandler=function(n){this.handler=n;return this;};m.prototype.send=function(){var n=this.handler,o=this.data,p=new Image();if(n)p.onload=p.onerror=function(){h.applyWithGuard(n,null,[p.height==1]);};o.asyncSignal=(Math.random()*10000|0)+1;var q=new j(this.uri).isFacebookURI();l(o,k.getAsyncParams(q?'POST':'GET'));p.src=i.appendToUrl(this.uri,o);return this;};e.exports=m;});
__d("legacy:async-signal",["AsyncSignal"],function(a,b,c,d){a.AsyncSignal=b('AsyncSignal');},3);
__d("legacy:uri",["URI"],function(a,b,c,d){a.URI=b('URI');},3);
function detect_broken_proxy_cache(a,b){var c=getCookie(b);if((c!=a)&&(c!=null)&&(a!='0')){var d={c:'si_detect_broken_proxy_cache',m:b+' '+a+' '+c},e=new URI('/common/scribe_endpoint.php').getQualifiedURI().toString();new AsyncSignal(e,d).send();}}
function link_rel_preload(){var a=/async(?:-post)?|dialog(?:-pipe|-post)?|theater|toggle/;document.documentElement.onmousedown=function(b){b=b||window.event;var c=b.target||b.srcElement,d=Parent.byTag(c,'A');if(!d)return;var e=d.getAttribute('ajaxify'),f=d.href,g=e||f;if(e&&f&&!(/#$/).test(f)){var h=b.which&&b.which!=1,i=b.altKey||b.ctrlKey||b.metaKey||b.shiftKey;if(h||i)return;}var j=d.rel&&d.rel.match(a);j=j&&j[0];switch(j){case 'dialog':case 'dialog-post':Bootloader.loadComponents('dialog');break;case 'dialog-pipe':Bootloader.loadComponents(['ajaxpipe','dialog']);break;case 'async':case 'async-post':Bootloader.loadComponents('async');break;case 'theater':Bootloader.loadComponents('PhotoSnowlift',function(){PhotoSnowlift.preload(g,d);});break;case 'toggle':Bootloader.loadComponents('Toggler');break;}return;};}
__d("DimensionTracking",["event-extensions","AsyncSignal","Cookie","DOMDimensions","isInIframe"],function(a,b,c,d,e,f){b('event-extensions');var g=b('AsyncSignal'),h=b('Cookie'),i=b('DOMDimensions'),j=b('isInIframe');function k(){var l=i.getViewportDimensions();h.set('wd',l.width+'x'+l.height);if(Math.random()<.01)new g('/ajax/dimension_context.php',{x:l.width,y:l.height}).send();}if(!j()){setTimeout(k,100);Event.listen(window,'resize',k);Event.listen(window,'focus',k);}});
__d("HighContrastMode",["AsyncSignal","Cookie","CSS","DOM","Env","Style"],function(a,b,c,d,e,f){var g=b('AsyncSignal'),h=b('Cookie'),i=b('CSS'),j=b('DOM'),k=b('Env'),l=b('Style'),m=null,n={init:function(o){if(m!==null&&o.currentState!=m)return;var p=j.create('div');j.appendContent(document.body,p);p.style.cssText='border: 1px solid;'+'border-color: red green;'+'position: fixed;'+'height: 5px;'+'top: -999px;'+'background-image: url('+o.spacerImage+');';var q=l.get(p,'background-image'),r=l.get(p,'border-top-color'),s=l.get(p,'border-right-color'),t=r==s||(q&&(q=='none'||q=='url(invalid-url:)'));if(t!=o.currentState){i.conditionClass(document.documentElement,'highContrast',t);if(k.user){h.set('hc',t?1:0);if(t)new g('/ajax/highcontrast').send();}}j.remove(p);m=t;}};e.exports=n;});